// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';
import Services from './Services/index.svelte';
import AboutSection from './AboutSection/index.svelte';
import ContactForm from './ContactForm/index.svelte';
import Testimonials from './Testimonials/index.svelte';
import FAQ from './FAQ/index.svelte';

export const components = {
	hero: Hero,
	rich_text: RichText,
	services: Services,
	about_section: AboutSection,
	contact_form: ContactForm,
	testimonials: Testimonials,
	faq: FAQ
};
