// Code generated by Slice Machine. DO NOT EDIT.

import FieldsExample from './FieldsExample/index.svelte';
import Hero from './Hero/index.svelte';
import Services from './Services/index.svelte';
import Testimonials from './Testimonials/index.svelte';
import FAQ from './FAQ/index.svelte';
import ContactForm from './ContactForm/index.svelte';
import AboutSection from './AboutSection/index.svelte';

export const components = {
	fields_example: FieldsExample,
	hero: Hero,
	services: Services,
	testimonials: Testimonials,
	faq: FAQ,
	contact_form: ContactForm,
	about_section: AboutSection
};
