// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Item in *Footer Settings → Business Hours*
 */
export interface FooterSettingsDocumentDataBusinessHoursItem {
	/**
	 * Hours field in *Footer Settings → Business Hours*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: i.e. Monday - Friday: 9:00 AM - 7:00 PM
	 * - **API ID Path**: footer_settings.business_hours[].hours
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	hours: prismic.KeyTextField;
}

/**
 * Item in *Footer Settings → Quick Links*
 */
export interface FooterSettingsDocumentDataQuickLinksItem {
	/**
	 * Label field in *Footer Settings → Quick Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.quick_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Footer Settings → Quick Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.quick_links[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer Settings documents
 */
interface FooterSettingsDocumentData {
	/**
	 * Description field in *Footer Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Write a brief descriptive caption...
	 * - **API ID Path**: footer_settings.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;

	/**
	 * Phone Number field in *Footer Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.phone_number
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_number: prismic.KeyTextField;

	/**
	 * Email field in *Footer Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;

	/**
	 * Address field in *Footer Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.address
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;

	/**
	 * Business Hours field in *Footer Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.business_hours[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	business_hours: prismic.GroupField<Simplify<FooterSettingsDocumentDataBusinessHoursItem>>;

	/**
	 * Quick Links field in *Footer Settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_settings.quick_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	quick_links: prismic.GroupField<Simplify<FooterSettingsDocumentDataQuickLinksItem>>;
}

/**
 * Footer Settings document from Prismic
 *
 * - **API ID**: `footer_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterSettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<FooterSettingsDocumentData>, 'footer_settings', Lang>;

type PageDocumentDataSlicesSlice =
	| FaqSlice
	| ContactFormSlice
	| TestimonialsSlice
	| ServicesSlice
	| AboutSectionSlice
	| HeroSlice
	| RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Company Name field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.company_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	company_name: prismic.KeyTextField;

	/**
	 * Tagline field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.tagline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tagline: prismic.KeyTextField;

	/**
	 * Logo field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * Email field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;

	/**
	 * Phone field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.phone
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone: prismic.KeyTextField;

	/**
	 * Address field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.address
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes = FooterSettingsDocument | PageDocument | SettingsDocument;

/**
 * Primary content in *AboutSection → Header → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
	/**
	 * Title field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: about_section.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Your journey to healing and growth starts here
	 * - **API ID Path**: about_section.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Content field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Share your story and mission...
	 * - **API ID Path**: about_section.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * Professional Image field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_section.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Call to Action Button Text field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Start Your Journey Today
	 * - **API ID Path**: about_section.default.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_button_text: prismic.KeyTextField;

	/**
	 * Call to Action Button Link field in *AboutSection → Header → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_section.default.primary.cta_button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Header variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutSectionSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *AboutSection → Item-Left → Primary*
 */
export interface AboutSectionSliceItemPrimary {
	/**
	 * Title field in *AboutSection → Item-Left → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: about_section.item.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *AboutSection → Item-Left → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Your journey to healing and growth starts here
	 * - **API ID Path**: about_section.item.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Content field in *AboutSection → Item-Left → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Share your story and mission...
	 * - **API ID Path**: about_section.item.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * Professional Image field in *AboutSection → Item-Left → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_section.item.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item-Left variation for AboutSection Slice
 *
 * - **API ID**: `item`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceItem = prismic.SharedSliceVariation<
	'item',
	Simplify<AboutSectionSliceItemPrimary>,
	never
>;

/**
 * Primary content in *AboutSection → Item-Right → Primary*
 */
export interface AboutSectionSliceItemRightPrimary {
	/**
	 * Title field in *AboutSection → Item-Right → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: About Us
	 * - **API ID Path**: about_section.itemRight.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *AboutSection → Item-Right → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Your journey to healing and growth starts here
	 * - **API ID Path**: about_section.itemRight.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Content field in *AboutSection → Item-Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Share your story and mission...
	 * - **API ID Path**: about_section.itemRight.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * Professional Image field in *AboutSection → Item-Right → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_section.itemRight.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item-Right variation for AboutSection Slice
 *
 * - **API ID**: `itemRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceItemRight = prismic.SharedSliceVariation<
	'itemRight',
	Simplify<AboutSectionSliceItemRightPrimary>,
	never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation =
	| AboutSectionSliceDefault
	| AboutSectionSliceItem
	| AboutSectionSliceItemRight;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: About section with image and text content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<'about_section', AboutSectionSliceVariation>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
	/**
	 * Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Get In Touch
	 * - **API ID Path**: contact_form.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Ready to start your healing journey?
	 * - **API ID Path**: contact_form.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Background Color field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Choose background color for the section
	 * - **API ID Path**: contact_form.default.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;

	/**
	 * Text Color field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Choose text color for good contrast
	 * - **API ID Path**: contact_form.default.primary.text_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	text_color: prismic.ColorField;

	/**
	 * Accent Color field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Choose accent color for buttons and highlights
	 * - **API ID Path**: contact_form.default.primary.accent_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	accent_color: prismic.ColorField;

	/**
	 * Layout Style field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.default.primary.layout
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	layout: prismic.SelectField<'form-left' | 'form-right' | 'centered' | 'split'>;

	/**
	 * Show Contact Information field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: contact_form.default.primary.show_contact_info
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	show_contact_info: prismic.BooleanField;

	/**
	 * Form Submit Button Text field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Send Message
	 * - **API ID Path**: contact_form.default.primary.form_submit_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	form_submit_text: prismic.KeyTextField;

	/**
	 * Success Message field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Thank you! We'll get back to you soon.
	 * - **API ID Path**: contact_form.default.primary.success_message
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	success_message: prismic.KeyTextField;

	/**
	 * Contact Info Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Contact Information
	 * - **API ID Path**: contact_form.default.primary.contact_info_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_info_title: prismic.KeyTextField;

	/**
	 * Encouraging Message Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Taking the first step takes courage
	 * - **API ID Path**: contact_form.default.primary.encouraging_message_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	encouraging_message_title: prismic.KeyTextField;

	/**
	 * Encouraging Message Text field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: We're here to support you. All conversations are confidential and we typically respond within 24 hours.
	 * - **API ID Path**: contact_form.default.primary.encouraging_message_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	encouraging_message_text: prismic.KeyTextField;

	/**
	 * Form Header Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Schedule Your First Session
	 * - **API ID Path**: contact_form.default.primary.form_header_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	form_header_title: prismic.KeyTextField;

	/**
	 * Form Header Description field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Please share some information about yourself and what brings you here today.
	 * - **API ID Path**: contact_form.default.primary.form_header_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	form_header_description: prismic.KeyTextField;

	/**
	 * Privacy Notice Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Your Privacy Matters
	 * - **API ID Path**: contact_form.default.primary.privacy_notice_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_notice_title: prismic.KeyTextField;

	/**
	 * Privacy Notice Text field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: All communications are strictly confidential and protected by professional counseling standards.
	 * - **API ID Path**: contact_form.default.primary.privacy_notice_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_notice_text: prismic.KeyTextField;

	/**
	 * Consent Checkbox Text field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: I understand that this form is secure and my information will be kept confidential. I consent to being contacted about scheduling an appointment.
	 * - **API ID Path**: contact_form.default.primary.consent_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	consent_text: prismic.KeyTextField;

	/**
	 * Success Message Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Thank You for Reaching Out
	 * - **API ID Path**: contact_form.default.primary.success_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	success_title: prismic.KeyTextField;

	/**
	 * Success Message Description field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: We've received your message and will respond within 24 hours. Taking this step shows real strength.
	 * - **API ID Path**: contact_form.default.primary.success_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	success_description: prismic.KeyTextField;

	/**
	 * Success Next Steps Text field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: What's next? We'll review your message and reach out to schedule a brief consultation where we can discuss your needs and answer any questions.
	 * - **API ID Path**: contact_form.default.primary.success_next_steps
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	success_next_steps: prismic.KeyTextField;
}

/**
 * Primary content in *ContactForm → Items*
 */
export interface ContactFormSliceDefaultItem {
	/**
	 * Contact Field Type field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: text
	 * - **API ID Path**: contact_form.items[].contact_field
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_field: prismic.KeyTextField;

	/**
	 * Field Label field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Full Name
	 * - **API ID Path**: contact_form.items[].field_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	field_label: prismic.KeyTextField;

	/**
	 * Field Placeholder field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter your full name
	 * - **API ID Path**: contact_form.items[].field_placeholder
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	field_placeholder: prismic.KeyTextField;

	/**
	 * Required Field field in *ContactForm → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: contact_form.items[].required
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	required: prismic.BooleanField;

	/**
	 * Field Options (for select fields) field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Option 1, Option 2, Option 3
	 * - **API ID Path**: contact_form.items[].field_options
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	field_options: prismic.KeyTextField;

	/**
	 * Contact Info Icon field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: phone
	 * - **API ID Path**: contact_form.items[].contact_info_icon
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_info_icon: prismic.KeyTextField;

	/**
	 * Contact Info Title field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Phone
	 * - **API ID Path**: contact_form.items[].contact_info_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_info_title: prismic.KeyTextField;

	/**
	 * Contact Info Content field in *ContactForm → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +1 (555) 123-4567
	 * - **API ID Path**: contact_form.items[].contact_info_content
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_info_content: prismic.KeyTextField;

	/**
	 * Contact Info Link (optional) field in *ContactForm → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_form.items[].contact_info_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_info_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactFormSliceDefaultPrimary>,
	Simplify<ContactFormSliceDefaultItem>
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: Contact form with customizable fields, styling, and contact information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<'contact_form', ContactFormSliceVariation>;

/**
 * Primary content in *FAQ → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
	/**
	 * Title field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Frequently Asked Questions
	 * - **API ID Path**: faq.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Common questions about our services
	 * - **API ID Path**: faq.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Contact Section Title field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Need More Information?
	 * - **API ID Path**: faq.default.primary.contact_section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_section_title: prismic.KeyTextField;

	/**
	 * Contact Section Description field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Every therapeutic journey is unique. If you have specific questions about your situation or our approach, we're here to help you feel fully informed and comfortable.
	 * - **API ID Path**: faq.default.primary.contact_section_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_section_description: prismic.KeyTextField;

	/**
	 * Contact Button 1 Text field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Send Us a Message
	 * - **API ID Path**: faq.default.primary.contact_button_1_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_button_1_text: prismic.KeyTextField;

	/**
	 * Contact Button 1 Link field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.default.primary.contact_button_1_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_button_1_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Contact Button 2 Text field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Call for a Consultation
	 * - **API ID Path**: faq.default.primary.contact_button_2_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_button_2_text: prismic.KeyTextField;

	/**
	 * Contact Button 2 Link field in *FAQ → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.default.primary.contact_button_2_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_button_2_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FAQ → Items*
 */
export interface FaqSliceDefaultItem {
	/**
	 * Question field in *FAQ → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: What can I expect in my first session?
	 * - **API ID Path**: faq.items[].question
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	question: prismic.KeyTextField;

	/**
	 * Answer field in *FAQ → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Provide a detailed answer to the question
	 * - **API ID Path**: faq.items[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;

	/**
	 * FAQ Category field in *FAQ → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq.items[].category
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<
		'general' | 'services' | 'pricing' | 'scheduling' | 'what-to-expect' | 'confidentiality'
	>;

	/**
	 * Featured Question field in *FAQ → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: faq.items[].featured
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	featured: prismic.BooleanField;
}

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FaqSliceDefaultPrimary>,
	Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Frequently asked questions with expandable content and customizable styling
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<'faq', FaqSliceVariation>;

/**
 * Item in *FieldsExample → Default → Primary → repeatable_group_label*
 */
export interface FieldsExampleSliceDefaultPrimaryRepeatableGroupLabelItem {
	/**
	 * text_in_group_label field in *FieldsExample → Default → Primary → repeatable_group_label*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.repeatable_group_label[].text_in_group_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text_in_group_label: prismic.KeyTextField;
}

/**
 * Primary content in *FieldsExample → Default → Primary*
 */
export interface FieldsExampleSliceDefaultPrimary {
	/**
	 * image_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.image_label
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image_label: prismic.ImageField<never>;

	/**
	 * text_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.text_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text_label: prismic.KeyTextField;

	/**
	 * rich_text_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.rich_text_label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	rich_text_label: prismic.RichTextField;

	/**
	 * link_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.link_label
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_label: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * select_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.select_label
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	select_label: prismic.SelectField<'1' | '2'>;

	/**
	 * boolean_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: fields_example.default.primary.boolean_label
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	boolean_label: prismic.BooleanField;

	/**
	 * number_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.number_label
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	number_label: prismic.NumberField;

	/**
	 * color_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.color_label
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	color_label: prismic.ColorField;

	/**
	 * date_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.date_label
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date_label: prismic.DateField;

	/**
	 * table_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Table
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.table_label
	 * - **Documentation**: https://prismic.io/docs/fields/table
	 */
	table_label: prismic.TableField;

	/**
	 * embed_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.embed_label
	 * - **Documentation**: https://prismic.io/docs/fields/embed
	 */
	embed_label: prismic.EmbedField;

	/**
	 * timestamp_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.timestamp_label
	 * - **Documentation**: https://prismic.io/docs/fields/timestamp
	 */
	timestamp_label: prismic.TimestampField;

	/**
	 * geopoint_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: GeoPoint
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.geopoint_label
	 * - **Documentation**: https://prismic.io/docs/fields/geopoint
	 */
	geopoint_label: prismic.GeoPointField;

	/**
	 * content_relationship_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.content_relationship_label
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	content_relationship_label: prismic.ContentRelationshipField<'page'>;

	/**
	 * link_to_media_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.link_to_media_label
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	link_to_media_label: prismic.LinkToMediaField<prismic.FieldState, never>;

	/**
	 * repeatable_group_label field in *FieldsExample → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: fields_example.default.primary.repeatable_group_label[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	repeatable_group_label: prismic.GroupField<
		Simplify<FieldsExampleSliceDefaultPrimaryRepeatableGroupLabelItem>
	>;
}

/**
 * Default variation for FieldsExample Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FieldsExampleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FieldsExampleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FieldsExample*
 */
type FieldsExampleSliceVariation = FieldsExampleSliceDefault;

/**
 * FieldsExample Shared Slice
 *
 * - **API ID**: `fields_example`
 * - **Description**: FieldsExample
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FieldsExampleSlice = prismic.SharedSlice<'fields_example', FieldsExampleSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Main Headline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Find Joy in Your Journey
	 * - **API ID Path**: hero.default.primary.main_headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	main_headline: prismic.KeyTextField;

	/**
	 * Sub Headline field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Professional counseling to help you heal, grow, and rediscover happiness
	 * - **API ID Path**: hero.default.primary.sub_headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	sub_headline: prismic.KeyTextField;

	/**
	 * Description field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Brief description of your counseling approach and mission
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Primary Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Schedule a Session
	 * - **API ID Path**: hero.default.primary.call_to_action_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	call_to_action_text: prismic.KeyTextField;

	/**
	 * Primary Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.call_to_action_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	call_to_action_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Secondary Button Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Learn More
	 * - **API ID Path**: hero.default.primary.secondary_button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_button_text: prismic.KeyTextField;

	/**
	 * Secondary Button Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.secondary_button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	secondary_button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Background Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
	/**
	 * Trust Indicator Text field in *Hero → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: HIPAA Compliant
	 * - **API ID Path**: hero.items[].trust_indicator_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	trust_indicator_text: prismic.KeyTextField;

	/**
	 * Trust Indicator Icon field in *Hero → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.items[].trust_indicator_icon
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	trust_indicator_icon: prismic.SelectField<
		'shield' | 'heart' | 'certificate' | 'calendar' | 'support' | 'confidential'
	>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with main content and call-to-action
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * Title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Our Services
	 * - **API ID Path**: services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Professional counseling services to help you heal and grow
	 * - **API ID Path**: services.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
	/**
	 * Service Title field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Individual Therapy
	 * - **API ID Path**: services.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Service Description field in *Services → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Describe what this service offers and how it helps clients
	 * - **API ID Path**: services.items[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Service Icon field in *Services → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon: prismic.SelectField<
		| 'heart'
		| 'brain'
		| 'conversation'
		| 'growth'
		| 'family'
		| 'couple'
		| 'mindfulness'
		| 'healing'
		| 'support'
		| 'wellness'
	>;

	/**
	 * Call to Action Text field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Book Session
	 * - **API ID Path**: services.items[].cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_text: prismic.KeyTextField;

	/**
	 * Call to Action Link field in *Services → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ServicesSliceDefaultPrimary>,
	Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services offered by the counseling practice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<'services', ServicesSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * Title field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: What Our Clients Say
	 * - **API ID Path**: testimonials.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Real stories from real people
	 * - **API ID Path**: testimonials.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
	/**
	 * Client Name field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sarah Johnson
	 * - **API ID Path**: testimonials.items[].client_name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	client_name: prismic.KeyTextField;

	/**
	 * Client Photo field in *Testimonials → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].client_photo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	client_photo: prismic.ImageField<never>;

	/**
	 * Star Rating field in *Testimonials → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.items[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	rating: prismic.SelectField<'5' | '4' | '3' | '2' | '1'>;

	/**
	 * Testimonial Text field in *Testimonials → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Share what the client said about their experience
	 * - **API ID Path**: testimonials.items[].testimonial_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	testimonial_text: prismic.RichTextField;

	/**
	 * Service Received field in *Testimonials → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Individual Therapy
	 * - **API ID Path**: testimonials.items[].service_received
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	service_received: prismic.KeyTextField;

	/**
	 * Session Date field in *Testimonials → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: When this testimonial was given
	 * - **API ID Path**: testimonials.items[].session_date
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	session_date: prismic.DateField;

	/**
	 * Featured Testimonial field in *Testimonials → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: testimonials.items[].featured
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	featured: prismic.BooleanField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TestimonialsSliceDefaultPrimary>,
	Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Client testimonials and reviews with customizable styling and layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterSettingsDocument,
			FooterSettingsDocumentData,
			FooterSettingsDocumentDataBusinessHoursItem,
			FooterSettingsDocumentDataQuickLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			AllDocumentTypes,
			AboutSectionSlice,
			AboutSectionSliceDefaultPrimary,
			AboutSectionSliceItemPrimary,
			AboutSectionSliceItemRightPrimary,
			AboutSectionSliceVariation,
			AboutSectionSliceDefault,
			AboutSectionSliceItem,
			AboutSectionSliceItemRight,
			ContactFormSlice,
			ContactFormSliceDefaultPrimary,
			ContactFormSliceDefaultItem,
			ContactFormSliceVariation,
			ContactFormSliceDefault,
			FaqSlice,
			FaqSliceDefaultPrimary,
			FaqSliceDefaultItem,
			FaqSliceVariation,
			FaqSliceDefault,
			FieldsExampleSlice,
			FieldsExampleSliceDefaultPrimaryRepeatableGroupLabelItem,
			FieldsExampleSliceDefaultPrimary,
			FieldsExampleSliceVariation,
			FieldsExampleSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceDefaultItem,
			HeroSliceVariation,
			HeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimary,
			ServicesSliceDefaultItem,
			ServicesSliceVariation,
			ServicesSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceDefaultItem,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault
		};
	}
}
